# Generated by Django 2.2.6 on 2019-11-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='rank',
            field=models.FloatField(default=0.0),
        ),
    ]
