# Generated by Django 2.2.6 on 2019-11-11 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='activation_code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='token',
        ),
    ]
